export const reducerCases = {
    SET_USER_INFO:"SET_USER_INFO",
    SET_NEW_USER: "SET_NEW_USER",
    SET_ALL_CONTACTS_PAGE:"SET_ALL_CONTACTS_PAGE",
    CHANGE_CURRENT_CHAT_USER: "CHANGE_CURRENT_CHAT_USER",
    SET_MESSAGES:"SET_MESSAGES",
    SET_MESSAGES_LOADING:"SET_MESSAGES_LOADING",
    ADD_MESSAGE: "ADD_MESSAGE",
    SET_MESSAGE_SEARCH:"SET_MESSAGE_SEARCH",
    SET_CONTACT_SEARCH:"SET_CONTACT_SEARCH",
    SET_CONTACT_FILTER:"SET_CONTACT_FILTER",
    SET_LANGUAGE:"SET_LANGUAGE",
};
